default_connection_name = "xpb58818"

[xpb58818]
account = "xpb58818"
user = "framirezl"
password = ${{ secrets.SNOWFLAKE_PASSWORD }}
authenticator = "snowflake"
SNOWFLAKE_ACCOUNT = "XJLIQNC-PGB38908.snowflakecomputing.com"
SNOWFLAKE_USER = "framirezl"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "PRUEBASCHEMACHANGE"
SNOWFLAKE_SCHEMA = "PUBLIC"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"