default_connection_name = "snow"

[snow]
account = "XJLIQNC-PGB38908"
user = "framirezl"
authenticator = "snowflake"
database = "PEDIDOS"
SNOWFLAKE_ACCOUNT = "XJLIQNC-PGB38908"
SNOWFLAKE_USER = "framirezl"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "PEDIDOS"
SNOWFLAKE_SCHEMA = "PUBLIC"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"