name: Deploy Snowflake Schema Changes

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install schemachange
      run: |
        pip install schemachange

    - name: Configure Snowflake Credentials
      run: |
          cat <<EOF > ./connections.toml
          default_connection_name = "snow"
          [connections]
          [snow]
          account = "XJLIQNC-PGB38908"
          user = "${{ vars.SNOWFLAKE_USER }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          database = "PEDIDOS"
          schema = "PUBLIC"
          warehouse = "COMPUTE_WH"
          rol = "ACCOUNTADMIN"


    - name: Run schemachange
      env:
        $env:SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: |
        schemachange -f scripts --connections-file-path connections.toml --connection-name snow \
        -c pruebaschemachange.public.CHANGE_HISTORY --create-change-history-table
     
