name: Deploy Snowflake Schema Changes

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install schemachange
      run: |
        pip install schemachange

    - name: Configure Snowflake Credentials
      run: |
          echo "[snow]" > connections.toml
          echo "account = \"XJLIQNC-PGB38908\"" >> connections.toml
          echo "user = \"${{ secrets.SNOWFLAKE_USER }}\"" >> connections.toml
          echo "password = \"${{ secrets.SNOWFLAKE_PASSWORD }}\"" >> connections.toml
          echo "role = \"ACCOUNTADMIN\"" >> connections.toml
          echo "warehouse = \"COMPUTE_WH\"" >> connections.toml
          echo "database = \"PEDIDOS"" >> connections.toml
          echo "schema = \"PUBLIC"" >> connections.toml

    - name: Run schemachange
      env:
        $env:SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: |
        schemachange -f scripts --connections-file-path connections.toml --connection-name snow \
        -c pruebaschemachange.public.CHANGE_HISTORY --create-change-history-table
     
