name: Deploy scripts to preprod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install snowflake-cli
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: ".snowflake/config.toml"

      - name: Configure Snowflake CLI
        run: |
          snow connection add --connection-name  "default" --account ${{ secrets.SNOWFLAKE_ACCOUNT }} --username ${{ secrets.SNOWFLAKE_USER }} --password ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Fetch repository changes
        run: snow git fetch lamosa_demo 

      - name: Deploy scripts to preprod environment
        run: snow git execute @lamosa_demo/main/scripts/* \
            -D "environment='preprod'"